run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - goimports
    - gocyclo
    - revive
    - goconst      # Finds repeated strings that could be replaced by constants
    - misspell     # Finds commonly misspelled English words
    - unconvert    # Remove unnecessary type conversions
    - unparam      # Reports unused function parameters
    - gosec        # Security checker - can catch SQL injection risks

linters-settings:
  gofumpt:
    extra-rules: true
  gocyclo:
    min-complexity: 15
  revive:
    severity: warning
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    # Check for SQL injection patterns
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)

issues:
  exclude-rules:
    - linters: [errcheck]
      text: "error return value not checked"
